### ISSUE TITLE
Questions about Explorer Cache

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [foundry-rs/block-explorers#51]
Hi all! 

I was checking the code of block explorer, but realize some tricky issues.

https://github.com/foundry-rs/block-explorers/blob/1f442fe1cc38c9fd7ecc2f9cc8ab102276ee0275/crates/block-explorers/src/contract.rs#L413-L430

Based on the code, it seems if the `cache.get_source(address) ` returns `None`, the function will throw `ContractCodeNotVerified` errors. 

However, based on the code of cache, there is another possibility that the contract is verified, *but the cache is not alive*. In that case, the function may misbehave.

https://github.com/foundry-rs/block-explorers/blob/1f442fe1cc38c9fd7ecc2f9cc8ab102276ee0275/crates/block-explorers/src/lib.rs#L472-L480

Please let me know if I misunderstood anything here. I am more than happy to open a PR if this is indeed an issue.

Thanks!

**Comment by ZhangZhuoSJTU** [comment]
It appears that, in many instances, the `cache` feature might not be enabled, even if the user intends to do so by setting the `Client.cache` field.

https://github.com/foundry-rs/block-explorers/blob/1f442fe1cc38c9fd7ecc2f9cc8ab102276ee0275/crates/block-explorers/src/lib.rs#L440-L458

When attempting to create `std::fs::File::create(path)`, the parent path (`self.root.join(prefix)`) likely does not exist. This path is intended for the cache directory, and it is uncommon for users to create it themselves. As a result, the operation might fail on some platforms, such as Ubuntu.

**Comment by mattsse** [comment]
> When attempting to create std::fs::File::create(path), the parent path (self.root.join(prefix)) likely does not exist.

yeah, we could try to create the dir first

**Comment by ZhangZhuoSJTU** [comment]
Thanks! I was debugging why the cache is not enabled and find the early (incorrect) issue 😂. Will have a very quick RP regarding this.

**Comment by ZhangZhuoSJTU** [comment]
close due to #52.
