### ISSUE TITLE
Remove `ethers-core` dependency

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/block-explorers#8]
Right now we're coupled to `ethers` due to using `RawAbi`, and the `Chain` enum. This means we need to keep patches on foundry to keep ethers versions in sync. We should remove the dep as follows:
- Integrate `alloy-rs/chains` when ready
- Move `RawAbi` into `block-explorers`, as it's not an alloy-related type nor an RPC type. It just uses some metadata from the ABI for verification purposes.

**Comment by DaniPopes** [comment]
`RawAbi` is not necessary anymore: https://github.com/foundry-rs/block-explorers/issues/10
